//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuroWebTools.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class ConfigFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigFile defaultInstance = ((ConfigFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigFile())));
        
        public static ConfigFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Common.Server.InstanceList ConnectionStringsInstance {
            get {
                return ((global::Common.Server.InstanceList)(this["ConnectionStringsInstance"]));
            }
            set {
                this["ConnectionStringsInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SRV-DVP02\\SQLDVP19")]
        public string ConnectionStringsServer {
            get {
                return ((string)(this["ConnectionStringsServer"]));
            }
            set {
                this["ConnectionStringsServer"] = value;
            }
        }
    }
}
