//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuroWebTools.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class CurrentWorkingOn : global::System.Configuration.ApplicationSettingsBase {
        
        private static CurrentWorkingOn defaultInstance = ((CurrentWorkingOn)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CurrentWorkingOn())));
        
        public static CurrentWorkingOn Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68424")]
        public int IssueNumber {
            get {
                return ((int)(this["IssueNumber"]));
            }
            set {
                this["IssueNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Common.Server.Version Version {
            get {
                return ((global::Common.Server.Version)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
    }
}
